version: '3'
services:
  DDTV.WEBServer:
    image: ghcr.io/chkzl/ddtv/webserver
    container_name: DDTV_WEB_Server
#   image: ghcr.io/chkzl/ddtv/cli
#   container_name: DDTV_CLI
#   command: ["--no-update", "--verbose"]
    restart: unless-stopped
    ports:
      - "11419:11419"
    environment:
      - "PUID=0"
      - "PGID=0"
      - "WebUserName=ami"
      - "WebPassword=ddtv"
      - "RoomListConfig=./RoomListConfig.json"
    volumes:
#     - DDTV:/DDTV
      - DDTV_Rec:/DDTV/Rec

volumes:
  DDTV_Rec:
# DDTV:
