version: '3'
# 修改详见 docker-compose-complete.yml
services:
  DDTV.WEBUI:
    image: moomiji/ddtvwebui
    container_name: DDTV_WEBUI
    restart: unless-stopped
    ports:
      - "11419:80"
    environment:
      PROXY_PASS: http://DDTV.WEBServer:11419
      apiUrl: "false"
      show: "false"
    networks:
      - public_access
      - service_only

  DDTV.WEBServer:
    image: moomiji/ddtv
    container_name: DDTV_WEBServer
    restart: unless-stopped
    environment:
      PUID: 0
      PGID: 0
      WebUserName: ami
      WebPassword: ddtv
      RoomListConfig_Path: ./RoomListConfig.json
    volumes:
  #    - DDTV_WEBServer:/DDTV
      - DDTV_Rec:/DDTV/Rec
    networks:
      - service_only

volumes:
  DDTV_Rec:
#  DDTV_WEBServer:    # /DDTV_WEBServer.path

networks:
  default: