version: '3'
services:
  DDTV.WEBUI:
    image: ghcr.io/chkzl/ddtv/webui
    container_name: DDTV_WEBUI
    restart: unless-stopped
    ports:
      - "11419:80"
    environment:
      - "PROXY_PASS=http://DDTV.WEBServer:11419"
      - "apiUrl=false"
      - "show=false"
    networks:
      - default

  DDTV.WEBServer:
    image: ghcr.io/chkzl/ddtv/webserver
    container_name: DDTV_WEBServer
#   command: ["--no-update", "--verbose"]
    restart: unless-stopped
    environment:
      - "PUID=0"
      - "PGID=0"
      - "WebUserName=ami"
      - "WebPassword=ddtv"
      - "RoomListConfig=./RoomListConfig.json"
    volumes:
#     - DDTV_WEBServer:/DDTV
      - DDTV_Rec:/DDTV/Rec
    networks:
      - default

volumes:
  DDTV_Rec:
# DDTV_WEBServer:

networks:
  default:
