name: DDTVLiveRec_docker
#若合并至源项目，以下要改：

#删去：
#  watch:
#    types: [started]

on:
  release:
    types: [released]
  watch:
    types: [started]
  push:
    branches: [master]
    paths:
      - Dockerfile.alpine
      - Dockerfile.debian
      - install.sh
      - start.sh
      - .github/workflows/DDTVLiveRec_docker.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ddtvliverec
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare
        id: prepare
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}"
          VERSION=$(curl -sX GET "https://api.github.com/repos/CHKZL/DDTV2/releases/latest" | awk '/tag_name/{print $4;exit}' FS='["]')
          TAG_VERSION="${IMAGE_NAME}:${VERSION}"
          TAG_LATEST="${IMAGE_NAME}:latest"
          echo ::set-output name=image_name::${IMAGE_NAME}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tag_version::${TAG_VERSION}
          echo ::set-output name=tag_latest::${TAG_LATEST}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to registry ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GITHUB_TOKEN }}

#构建各架构镜像
      - name: Build and push debian os
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.debian
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          build-args: ${{ steps.prepare.outputs.version }}
          tags: |
            ${{ steps.prepare.outputs.tag_version }}-debian
            ${{ steps.prepare.outputs.tag_latest }}-debian
            ghcr.io/${{ steps.prepare.outputs.tag_version }}-debian
            ghcr.io/${{ steps.prepare.outputs.tag_latest }}-debian

      - name: Build and push alpine os
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          build-args: ${{ steps.prepare.outputs.version }}
          tags: |
            ${{ steps.prepare.outputs.tag_version }}
            ${{ steps.prepare.outputs.tag_latest }}
            ghcr.io/${{ steps.prepare.outputs.tag_version }}
            ghcr.io/${{ steps.prepare.outputs.tag_latest }}
