name: DDTV_WEB_Server_Docker

on:
  release:
    types: [released]
  watch:
    types: [started]
  push:
    branches: [master]
    paths:
      - 'Docker/**'
      - 'Docker/README.md'
      - '.github/workflows/DDTV_WEB_Server_Docker.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Prepare
        id: prepare
        run: |
          echo ::set-output name=ddtv_version::$(curl -sX GET "https://api.github.com/repos/CHKZL/DDTV/releases/latest" | awk '/tag_name/{print $4;exit}' FS='["]')
          cd Docker/ && chmod +x prepare.sh && ./prepare.sh

      - name: Metadata for alpine images
        id: alpine
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ddtvliverec
            ghcr.io/${{ github.actor }}/ddtvliverec
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.prepare.outputs.ddtv_version }}

      - name: Metadata for debian images
        id: debian
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ddtvliverec
            ghcr.io/${{ github.actor }}/ddtvliverec
          flavor: |
            latest=true
            suffix=-debian,onlatest=true
          tags: |
            type=raw,value=${{ steps.prepare.outputs.ddtv_version }}

# 登录至仓库
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GITHUB_TOKEN }}

# 构建各架构镜像
      - name: Build and push debian os
        uses: docker/build-push-action@v2
        with:
          context: Docker/
          file: Docker/Dockerfile.debian
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.debian.outputs.tags }}
          labels: ${{ steps.debian.outputs.labels }}

      - name: Build and push alpine os
        uses: docker/build-push-action@v2
        with:
          context: Docker/
          file: Docker/Dockerfile.alpine
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.alpine.outputs.tags }}
          labels: ${{ steps.alpine.outputs.labels }}
