name: DDTVLiveRec_docker_test

on:
  workflow_dispatch:
  push:
    branches: 
      - test

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ddtvliverec
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prepare
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_TEST_USERNAME }}/${{ env.IMAGE_NAME }}"
          echo ::set-output name=image_name::${IMAGE_NAME}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_TEST_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#构建各架构镜像
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.test
          platforms: linux/amd64
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: |
            ${{ steps.prepare.outputs.image_name }}:test
