name: test

on:
  workflow_dispatch:
    inputs:
      push:
        required: true
        type: boolean
        default: true
  push:
    branches: [test]
    paths:
      - '.github/workflows/test.yml'

jobs:
  meta:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        version: [12, 14, 16]
        environment: [staging, production]
        exclude:
          - os: macos-latest
            version: 12
            environment: production
          - os: windows-latest
            version: 16
    runs-on: ubuntu-latest
    steps:
      - id: set_tag
        run: |
          is_release=false
          tag=1.2.3.4-0-222
          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            next=${prefix##*.}
            ((next++))
            prefix=${prefix%.*}
            tag="$prefix.$next-Preview.$suffix"
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo version=${tag#v} | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
