name: test

on:
  workflow_dispatch:
    inputs:
      push:
        required: true
        type: boolean
        default: true
  push:
    branches: [test]
    paths:
      - '.github/workflows/test.yml'

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output Version
        id: version
        run: |
          echo "::warning file=./.github/workflows/test.yml,line=1::Missing semicolon"
