name: test

on:
  workflow_dispatch:
    inputs:
      push:
        required: true
        type: boolean
        default: true
  push:
    branches: [test]
    paths:
      - '.github/workflows/test.yml'

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - id: set_tag
        run: |
          is_release=true
          tag=v0.3.6

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT

  ABC:
    needs: [meta]
    if: ${{ needs.meta.outputs.is_release }}
    runs-on: ubuntu-latest
    steps:
      - name: Publish Nupkgs
        if: ${{ needs.meta.outputs.is_release }}
        working-directory: pkgs/nupkgs
        run: |
          echo ${{ needs.meta.outputs.is_release }}
